### ISSUE TITLE
Refactor data structures

### ISSUE THREAD

**Issue by kbroman** [rqtl/qtl2geno#105]
I'm thinking I should simplify a number of the data structures, particularly to make it easier for others to make use of some of the [qtl2scan](https://github.com/rqtl/qtl2scan) code without using our HMM stuff in [qtl2geno](https://github.com/rqtl/qtl2geno).

In particular, the genotype probability object produced by `calc_genoprob` could just be a list of arrays, and not include the genetic map. Similarly, the output of `scan1` need not include the genetic map.

For downstream plots and summaries, the user would need to provide both the `scan1` results and the map. And the function to insert pseudomarker positions, which is currently called internally in the `calc_genoprob` and related functions, would need to be called by the user, and the result passed to `calc_genoprob`. So if pseudomarkers were to be inserted, there would be one more step for the user.

I think also I should strip off much of the stuff in the output of `scan1`, about what covariates were used and so forth. It's potentially convenient to have that clear within the results, but I think it's just as well to leave it to the user to keep track of what code was used to produce a particular object.

For the output of `scan1` with a linear mixed model, I think I'll move the estimated heritabilities to be an attribute, and then write a helper function for pulling those out. The central object would be simpler: just a data frame with LOD scores, with marker/pseudomarker names in the row names.

**Comment by kbroman** [comment]
A bit more on this point...

Currently, we'd do a genome scan something like this:

```
mydata <- read_cross2("mydata.zip")
pr <- calc_genoprob(mydata, step=1)
apr <- genoprob_to_alleleprob(pr)
out <- scan1(apr, mydata$pheno)
plot(out)
```

The new version would be something like this:

```
mydata <- read_cross2("mydata.zip")
gmap_pmar <- insert_pseudomarkers(mydata$gmap, step=1)
pr <- calc_genoprob(mydata, gmap_pmar)
apr <- genoprob_to_alleleprob(pr)
out <- scan1(apr, mydata$pheno)
plot(out, gmap_pmar)
```

Analysis without inserting any pseudomarkers would have one fewer steps:

```
mydata <- read_cross2("mydata.zip")
pr <- calc_genoprob(mydata, mydata$gmap)
apr <- genoprob_to_alleleprob(pr)
out <- scan1(apr, mydata$pheno)
plot(out, mydata$gmap)
```

**Comment by sens** [comment]
What happens if you give a different (wrong) map to the `scan1` object below?

```
out <- scan1(apr, mydata$pheno)
plot(out, anotherdata$gmap)
```

The advantage of having the `scan1` object containing the map is that the plot works as expected.  How about the output of `scan1` being a dataframe including the map?

In general I support the idea of the outputs being data frames, with other information being added as attributes, or with optional list items.

**Comment by byandell** [comment]
As Karl states, the map is not used by scan1, which relies on the allele probabilities `apr`. The map comes in for computing `pr` or making a plot. One could have an umbrella function to address the bookkeeping aspect of `scan1`:

```
mydata_to_scan1 <- function(mydata,
      apr = genoprob_to_alleleprob(pr),
      pr = calc_genoprob(mydata, mydata$gmap)) {
  scan1(apr, mydata$pheno)
}
out <- mydata_to_scan1(mydata)
```

That is, the user could supply `apr` or `pr`. For instance, compute `pr` adding pseudomarkers:

```
gmap_pmar <- insert_pseudomarkers(mydata$gmap, step=1)
pr <- calc_genoprob(mydata, gmap_pmar)
out <- mydata_to_scan1(mydata, pr = pr)
```

**Comment by byandell** [comment]
Saunak says: "I would prefer the map object to be a data frame instead of a list.
It would be easier for other programs (and languages) to use a data
frame."

If the map object is a data frame, it would have columns for chr and pos, and maybe type of chromosome (A, X, Y, M).

I like this idea, even though it takes more space than a list. I would also like to consider the genoprobs as a tall data frame (columns for ind, allele, mar, chr, prob) rather than a list of arrays. This way it can be indexed in an SQL for instance for fine mapping.

**Comment by kbroman** [comment]
For most of the operations I perform on a map, the list version is a bit easier. I'm thinking it's okay to deviate from the table format as long as we have helper functions like `table2map()` and `map2table()` (or actually, in [qtl2convert](https://github.com/rqtl/qtl2convert) I called them [`map_list_to_df`](https://github.com/rqtl/qtl2convert/blob/master/R/map_list_to_df.R) and [`map_df_to_list`](https://github.com/rqtl/qtl2convert/blob/master/R/map_df_to_list.R)).

**Comment by kbroman** [comment]
It seems like a tall table format for the genoprobs would be really huge. I'd be inclined, again, towards helper functions to pull out desired slices, or helper functions to convert from the list of arrays to the tall table, and back again.

**Comment by byandell** [comment]
Karl, you are right. I thought perhaps there would be many zeroes (or below tolerance) values that could be removed. While that appears to be the case for haplotype allele probas, it does not hold for SNPs or for 36 diplotypes. And, such a refactoring would involve a lot of recoding. Not worth it.

Below is an example on chr 3, with scan window spanning 135-145Mbp

8 haplotype allele probabilities (whole chr 3):

```
> dim(probs_obj$probs[[1]])
[1]  380    8 7068
> length(probs_obj$probs[[1]])
[1] 21486720
> sum(probs_obj$probs[[1]] == 0)
[1] 0
> sum(abs(probs_obj$probs[[1]]) < 1e-16)
[1] 12761362
> sum(abs(probs_obj$probs[[1]]) > 1e-16)
[1] 8725358
```

SNP probabilites in scan window:

```
> snpprobs_obj <- get_snpprobs(chr_id, 
+                    peak_Mbp, 
+                    window_Mbp,
+                    pheno_names, 
+                    probs_obj,
+                    datapath)
> dim(snpprobs_obj$probs[[1]])
[1]  380    2 6619
> length(snpprobs_obj$probs[[1]])
[1] 5030440
> sum(abs(snpprobs_obj$probs[[1]]) > 1e-16)
[1] 3650338
> sum(abs(snpprobs_obj$probs[[1]]) < 1e-16)
[1] 1380102
```

36 diplotype allele probabilities:

```
> probs36_obj <- read_probs36(chr_id, 
+                             scan_window[1],
+                             scan_window[2],
+                             datapath)
> dim(probs36_obj$probs[[1]])
[1] 400  36 501
> length(probs36_obj$probs[[1]])
[1] 7214400
> sum(abs(probs36_obj$probs[[1]]) > 1e-16)
[1] 5851126
> sum(abs(probs36_obj$probs[[1]]) < 1e-16)
[1] 1363274
```

3-level SNP probabilities in scan window:

```
> snpprobs36_obj <- get_snpprobs(chr_id, 
+                                peak_Mbp, 
+                                window_Mbp,
+                                pheno_names, 
+                                probs36_obj,
+                                datapath)
> dim(snpprobs36_obj$probs[[1]])
[1]  400    3 9821
> length(snpprobs36_obj$probs[[1]])
[1] 11785200
> sum(abs(snpprobs36_obj$probs[[1]]) > 1e-16)
[1] 10875163
> sum(abs(snpprobs36_obj$probs[[1]]) < 1e-16)
[1] 910037
```

**Comment by pjotrp** [comment]
@sens  I agree with the new definition. It is best to have inputs explicit - so you can see at a bird's view what goes in and what is used. Opaque objects, such as mydata, may intrpduce side effects - especially when used to store intermediate results. For example, order of methods may change what is under the hood. This can introduce subtly bugs and also makes it harder to support users. I think mydata should only contain original data and considered *immutable* to make for clear code. Much in the Julia way ;)

**Comment by dmgatti** [comment]
I like the idea of keeping the map with the scan output. There have been several times where I plotted DOQTL data with a map that was slightly off and it takes a while to find the error. qtl2 has an rbind function to bind together multiple scans, so users don't have to have multiple copies of the map when scanning multiple phenotypes.

I prefer to plot scans on a Mb scale and I think that most users do as well. But you need the cM values for haplotype reconstruction.  So I think that you can keep both in the markers object.  A data.frame is easier for most users to use. You can split it by chromosome fairly easily for internal use.

**Comment by kbroman** [comment]
Revised and now released; changes described in <http://kbroman.org/qtl2/assets/vignettes/version05_new.html>.
