### ISSUE TITLE
qtl2geno and qtlscan installation error

### ISSUE THREAD

**Issue by rajanikanthnmsu** [rqtl/qtl2geno#12]
I am trying to install qtl2geno and qtlscan via github. but i am getting the following error.

ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [qtl2geno.so] Error 1
ERROR: compilation failed for package ‘qtl2geno’
- removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/qtl2geno’
  Error: Command failed (1)

---

Could you please suggest me what is wrong.

Thanks
-Raj

**Comment by kbroman** [comment]
You need to install fortran. See http://r.research.att.com/tools/

**Comment by rajanikanthnmsu** [comment]
Thanks. I will try it.

**Comment by kbroman** [comment]
The ReadMe files now mention the need for a fortran compiler.
