### ISSUE TITLE
qtl2 Installation fail.

### ISSUE THREAD

**Issue by ariverosw** [rqtl/qtl2geno#13]
Hi I'm trying to install the version 2 of the qtl package and the process crushed. 

R session Aborted
R encountered a fatal error
The session was terminated

I load the devtools library and the send this command:

install_github(c("rqtl/qtl2geno", "rqtl/qtl2scan"))

After this is when R crushed.

Before this I was told to updated my R version.

Thanks!
Alejandro

This is the R version I have installed in my computer.

platform       x86_64-apple-darwin13.4.0
arch           x86_64
os             darwin13.4.0
system         x86_64, darwin13.4.0
status
major          3
minor          2.2
year           2015
month          08
day            14
svn rev        69053
language       R
version.string R version 3.2.2 (2015-08-14)
nickname       Fire Safety

**Comment by kbroman** [comment]
R/qtl2 is not quite ready for general use, but I've not seen a crash on installation.

But to figure out what's going on, it would help if you'd provide more detail on the output up to the point of the crash. And can you tell whether it's crashing from qtl2geno or from qtl2scan?

Can you install other packages with devtools?

**Comment by ariverosw** [comment]
Hi thanks for the quick replay!!!

Now I tried to install (devtools again) on R (not Rstudio) and I got this:

Downloading github repo hadley/devtools@master

 **\* caught segfault ***
address 0xcb8, cause 'memory not mapped'

Traceback:
 1: .Call("R_curl_easy_init", PACKAGE = "RCurl")
 2: RCurl::getCurlHandle(cookiefile = cookie_path, .defaults = list())
 3: handle(handle_name)
 4: find_handle(url)
 5: handle_url(handle, url, ...)
 6: httr::GET(url, ...)
 7: download(dest, src, auth)
 8: remote_download.github_remote(remote, quiet = quiet)
 9: remote_download(remote, quiet = quiet)
10: FUN(X[[i]], ...)
11: vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
12: install_remotes(remotes, ...)
13: devtools::install_github("hadley/devtools")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:

Is the same when I tried to install qtl2. I did not try to install qtl2geno
or from qtl2scan separately.
Apparently installing a package from github is giving me problems since
this fails.

devtools::install_github("hadley/devtools")

I guess I have to issue a report with devtools now.

Thanks,
Alejandro

**Comment by kbroman** [comment]
Try installing devtools from CRAN:

```
install.packages("devtools")
```

**Comment by ariverosw** [comment]
Yes that was already installed before I tried to install qtl2. I removed
and reinstalled it but is still giving the same problem.

**Comment by kbroman** [comment]
But the error you showed looked like an error while installing devtools:

```
Downloading github repo hadley/devtools@master

 *** caught segfault ***
address 0xcb8, cause 'memory not mapped'
```

**Comment by ariverosw** [comment]
Yes but the error was similar. Now R is not working and it looks like is
because of the package "devtools". I'll see what I can do to fix it and
keep using R qtl for now.
Thank you very much for the help!!!
Alejandro
