### ISSUE TITLE
iron dataset: warning followed by segfault 

### ISSUE THREAD

**Issue by simecek** [rqtl/qtl2geno#35]
Both

iron <- read_cross2("http://kbroman.org/qtl2/assets/sampledata/iron/iron.zip")

and

iron2 <- read_cross2(system.file("extdata", "iron.zip", package="qtl2geno"))

give me the following warning I do not understand

Warning message:
In data.table::fread(filename, na.strings = na.strings, sep = sep,  :
  Bumped column 2 to type character on data row 65, field contains 'X'. Coercing previously read values in this column from logical, integer or numeric back to character which may not be lossless; e.g., if '00' and '000' occurred before they will now be just '0', and there may be inconsistencies with treatment of ',,' and ',NA,' too (if they occurred in this column before the bump). If this matters please rerun and set 'colClasses' to 'character' for this column. Please note that column type detection uses the first 5 rows, the middle 5 rows and the last 5 rows, so hopefully this message should be very rare. If reporting to datatable-help, please rerun and include the output from verbose=TRUE.

When I try to estimate the map, I get segmentation fault 

> est_map(iron)

**\* caught segfault ***
address (nil), cause 'unknown'
Segmentation fault (core dumped)

The error is iron dataset specific, grav2 works fine.

R version 3.1.2 (2014-10-31)
Platform: x86_64-unknown-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] qtl2geno_0.3-12

loaded via a namespace (and not attached):
[1] Rcpp_0.11.4

**Comment by kbroman** [comment]
The weird messages that `read_cross2` gives are coming from `data.table::fread()`. If you upgrade to the latest version of data.table, I think I've been able to suppress them.

I'll work on the seg fault.

**Comment by kbroman** [comment]
For the first part (warning in `read_cross2`), I was wrong that this had been eliminated in the latest version of data.table. I'm going to get around it by reading in the data with `colClasses="character"` and then converting the appropriate things to numeric afterwards. See PR [36](https://github.com/rqtl/qtl2geno/pull/36).

Still need to work on the seg fault. 😦

**Comment by simecek** [comment]
Confirm. Tried both stable data.table 1.9.6 and development data.table 1.9.7 and got the warning.

I do not use data.table, but it may be connected to https://github.com/Rdatatable/data.table/issues/504

**Comment by kbroman** [comment]
Seems like `est_map` gives a seg fault when there are exactly two markers on a chromosome.

**Comment by kbroman** [comment]
Fixed in PR #38.
