### ISSUE TITLE
Enhance treatment of parallel analysis to facility multi-node clusters

### ISSUE THREAD

**Issue by kbroman** [rqtl/qtl2geno#7]
@simecek had asked that the parallel processing code be revised to make it easier to use multi-node clusters.

I think what he wants is to be able to first run `parallel::makeCluster` and then pass the set of clusters to a function.

Maybe the `n_cores` argument in functions like `calc_genoprob` and `est_map` could be called `cores` and either be an integer (in which case it is interpreted now: the desired number of cores) or be the result of `makeCluster`.

**Comment by kbroman** [comment]
Made an attempt in PR #20; don't have a setup on which to test it.

**Comment by simecek** [comment]
Karl, I have run it and confirm it works in principle

> system.time(gmap <- est_map(grav2, error_prob=0.002, cores=1))
>    user  system elapsed
>   4.604   0.002   4.608

cl <- makeCluster(5)

> system.time(gmap <- est_map(grav2, error_prob=0.002, cores=cl))
>    user  system elapsed
>   0.011   0.002   3.060

To really see the benefits, I need to find a task with >1 minute of running time. Ideally, not memory intensive. Any idea?

**Comment by kbroman** [comment]
Since it seemed to work, I'm going to close this.
